### ISSUE TITLE
compilation fail with rebar3

### ISSUE THREAD

**Issue by benoitc** [uwiger/setup#24] opened 2016-04-02 19:40 UTC
compile hooks makes the compilation crash the first time you launch it with rebar3.

``` shell
===> Compiling setup
===> run_hooks("/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup", pre_hooks, compile) -> no hooks defined

===> run_hooks("/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup", pre_hooks, erlc_compile) -> no hooks defined

===> erlopts [debug_info,debug_info]
===> files to compile ["/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup/src/setup_lib.erl",
                              "/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup/src/setup_gen.erl",
                              "/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup/src/setup.erl"]
===>      Compiled setup_lib.erl
===>      Compiled setup_gen.erl
===>      Compiled setup.erl
===> run_hooks("/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup", pre_hooks, app_compile) -> no hooks defined

===> sh info:
        cwd: "/Users/benoitc/Projects/barrel-platform"
        cmd: git log -n 1 --pretty=format:"%h
"

===>    opts: [{use_stdout,false},
                       return_on_error,
                       {cd,"/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup"}]

===> Port Cmd: git log -n 1 --pretty=format:"%h
"
Port Opts: [{cd,"/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof]

===> sh info:
        cwd: "/Users/benoitc/Projects/barrel-platform"
        cmd: git log --oneline --no-walk --tags --decorate

===>    opts: [{use_stdout,false},
                       return_on_error,
                       {cd,"/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup"}]

===> Port Cmd: git log --oneline --no-walk --tags --decorate
Port Opts: [{cd,"/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof]

===> sh info:
        cwd: "/Users/benoitc/Projects/barrel-platform"
        cmd: git rev-list 1.6..HEAD

===>    opts: [{use_stdout,false},
                       {cd,"/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup"},
                       {debug_abort_on_error,
                           "Getting rev-list of git dep failed in /Users/benoitc/Projects/barrel-platform/_build/default/lib/setup"}]

===> Port Cmd: git rev-list 1.6..HEAD
Port Opts: [{cd,"/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof]

===> sh info:
        cwd: "/Users/benoitc/Projects/barrel-platform"
        cmd: compile escriptize

===>    opts: [use_stdout,
                       {cd,"/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup"},
                       {env,[{"REBAR_DEPS_DIR",
                              "/Users/benoitc/Projects/barrel-platform/_build/default/lib"},
                             {"REBAR_BUILD_DIR",
                              "/Users/benoitc/Projects/barrel-platform/_build/default"},
                             {"REBAR_ROOT_DIR",
                              "/Users/benoitc/Projects/barrel-platform/."},
                             {"REBAR_CHECKOUTS_DIR",
                              "/Users/benoitc/Projects/barrel-platform/_checkouts"},
                             {"REBAR_PLUGINS_DIR",
                              "/Users/benoitc/Projects/barrel-platform/_build/default/plugins"},
                             {"REBAR_GLOBAL_CONFIG_DIR",
                              "/Users/benoitc/.config/rebar3"},
                             {"REBAR_GLOBAL_CACHE_DIR",
                              "/Users/benoitc/.cache/rebar3"},
                             {"REBAR_TEMPLATE_DIR",
                              "/Users/benoitc/.config/rebar3/templates"},
                             {"REBAR_APP_DIRS",
                              "/Users/benoitc/Projects/barrel-platform/_build/default/apps/*:/Users/benoitc/Projects/barrel-platform/_build/default/lib/*:/Users/benoitc/Projects/barrel-platform/_build/default/."},
                             {"REBAR_SRC_DIRS",[]},
                             {"ERLANG_ERTS_VER","7.1"},
                             {"ERLANG_ROOT_DIR",
                              "/Users/benoitc/local/otp/18.1.3"},
                             {"ERLANG_LIB_DIR_erl_interface",
                              "/Users/benoitc/local/otp/18.1.3/lib/erl_interface-3.8"},
                             {"ERLANG_LIB_VER_erl_interface","3.8"},
                             {"ERL","/Users/benoitc/local/otp/18.1.3/bin/erl"},
                             {"ERLC",
                              "/Users/benoitc/local/otp/18.1.3/bin/erlc"},
                             {"ERLANG_ARCH","64"},
                             {"ERLANG_TARGET",
                              "18.1.3-x86_64-apple-darwin15.0.0-64"}]},
                       {abort_on_error,"Hook for compile failed!\n"}]

===> Port Cmd: compile escriptize
Port Opts: [{cd,"/Users/benoitc/Projects/barrel-platform/_build/default/lib/setup"},
            {env,[{"REBAR_DEPS_DIR",
                   "/Users/benoitc/Projects/barrel-platform/_build/default/lib"},
                  {"REBAR_BUILD_DIR",
                   "/Users/benoitc/Projects/barrel-platform/_build/default"},
                  {"REBAR_ROOT_DIR",
                   "/Users/benoitc/Projects/barrel-platform/."},
                  {"REBAR_CHECKOUTS_DIR",
                   "/Users/benoitc/Projects/barrel-platform/_checkouts"},
                  {"REBAR_PLUGINS_DIR",
                   "/Users/benoitc/Projects/barrel-platform/_build/default/plugins"},
                  {"REBAR_GLOBAL_CONFIG_DIR","/Users/benoitc/.config/rebar3"},
                  {"REBAR_GLOBAL_CACHE_DIR","/Users/benoitc/.cache/rebar3"},
                  {"REBAR_TEMPLATE_DIR",
                   "/Users/benoitc/.config/rebar3/templates"},
                  {"REBAR_APP_DIRS",
                   "/Users/benoitc/Projects/barrel-platform/_build/default/apps/*:/Users/benoitc/Projects/barrel-platform/_build/default/lib/*:/Users/benoitc/Projects/barrel-platform/_build/default/."},
                  {"REBAR_SRC_DIRS",[]},
                  {"ERLANG_ERTS_VER","7.1"},
                  {"ERLANG_ROOT_DIR","/Users/benoitc/local/otp/18.1.3"},
                  {"ERLANG_LIB_DIR_erl_interface",
                   "/Users/benoitc/local/otp/18.1.3/lib/erl_interface-3.8"},
                  {"ERLANG_LIB_VER_erl_interface","3.8"},
                  {"ERL","/Users/benoitc/local/otp/18.1.3/bin/erl"},
                  {"ERLC","/Users/benoitc/local/otp/18.1.3/bin/erlc"},
                  {"ERLANG_ARCH","64"},
                  {"ERLANG_TARGET","18.1.3-x86_64-apple-darwin15.0.0-64"}]},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof]

sh: line 0: exec: compile: not found
===> Hook for compile failed!
```

**Comment by uwiger** [comment] 2016-04-03 07:29
Still trying to work my way up to using rebar3, but things keep getting in the way. ;-)

AFAIK, there is only one hook in setup: the post_hook to call escriptize. Is there a more robust way to do that in rebar3?

**Comment by benoitc** [comment] 2016-04-06 18:01
you can use the `escriptize` command:
http://www.rebar3.org/docs/commands#escriptize

Other way is to use erlang.mk ;)

**Comment by uwiger** [comment] 2016-04-06 20:19
See PR #25 - could you try and see if it solves your problem?

**Comment by benoitc** [comment] 2016-04-14 07:57
last commit fixed it. Thanks! Would be cool if you could make a release so exometer could use it :)

**Comment by MSch** [comment] 2016-06-28 12:39
I'm still getting this error with 1.8.0 when compiling with rebar3 using the package from hex:

```
===> Load global config file /Users/msch/.config/rebar3/rebar.config
===> Expanded command sequence to be run: []
===> Expanded command sequence to be run: [{default,app_discovery},
                                           {bare,compile}]
===> Evaluating config script "/Users/msch/tmp/st/deps/setup/rebar.config.script"
===> Compiling setup
===> erlopts [debug_info,debug_info]
===> files to compile ["/Users/msch/tmp/st/deps/setup/src/setup_sup.erl",
                       "/Users/msch/tmp/st/deps/setup/src/setup_srv.erl",
                       "/Users/msch/tmp/st/deps/setup/src/setup_lib.erl",
                       "/Users/msch/tmp/st/deps/setup/src/setup_gen.erl",
                       "/Users/msch/tmp/st/deps/setup/src/setup_app.erl",
                       "/Users/msch/tmp/st/deps/setup/src/setup.erl"]
===> Unable to run post hooks for 'compile', command 'escriptize' not found.
===> Unable to run post hooks for 'compile', command 'escriptize' not found.
** (Mix) Could not compile dependency :setup, "/Users/msch/.bin/rebar3 bare compile --paths "/Users/msch/tmp/st/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile setup", update it with "mix deps.update setup" or clean it with "mix deps.clean setup"
```

**Comment by uwiger** [comment] 2016-06-28 14:07
I can't reproduce this.

I created a simple application from scratch and added setup-1.8.0 as a dep:

```
uwpro:test uwiger$ cat rebar.config
{deps, [{setup, "1.8.0"}]}.

uwpro:test uwiger$ rebar3 compile
===> Package setup-1.8.0 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /Users/uwiger/.cache/rebar3/hex/default/registry
===> Generating package index...
===> [cloudi_service_oauth1:1.5.1] Only existing version of cloudi_service_db_riak is 1.3.3 which does not match constraint ~> 1.5.1. Using anyway, but it is not guaranteed to work.
===> Writing index to /Users/uwiger/.cache/rebar3/hex/default/packages.idx
===> Verifying dependencies...
===> Fetching setup ({pkg,<<"setup">>,<<"1.8.0">>})
===> Downloaded package, caching at /Users/uwiger/.cache/rebar3/hex/default/packages/setup-1.8.0.tar
===> Compiling setup
===> Building escript...
===> Compiling test
uwpro:test uwiger$ ls _build/default/lib/setup/ebin/
setup.app	setup_app.beam	setup_lib.beam	setup_sup.beam
setup.beam	setup_gen.beam	setup_srv.beam
```

**Comment by MSch** [comment] 2016-06-28 14:13
@uwiger I tried reproducing as well, and it only happens in an Elixir mix project, not when using a Erlang rebar3 project. Not sure how to narrow this down further. :/

**Comment by cmullaparthi** [comment] 2016-09-02 15:16
I had this problem. See #35 for a fix.

**Comment by uwiger** [comment] 2016-09-03 10:46
I'll happily merge, but don't have time to try to verify.
I'm perfectly willing to trust you though. :)

**Comment by uwiger** [comment] 2016-09-03 10:47
#35 merged.

**Comment by tolbrino** [comment] 2016-11-07 09:10
Then I guess this is resolved?

**Comment by MSch** [comment] 2016-12-01 02:25
Still failing for me


```
===> Compiling setup
===> Unable to run post hooks for 'compile', command 'escriptize' not found.
```

**Comment by uwiger** [comment] 2016-12-01 08:15
I have not yet migrated to rebar3 in the current project where I'm using setup.
Can anybody else compare notes?

**Comment by tolbrino** [comment] 2017-02-03 08:24
@MSch Could you test whether #38 solves your issue?

**Comment by danigulyas** [comment] 2017-03-07 14:34
Hi!

Context: I'm using it to build our project, not sure which deps pulls it in.
Cluses:
* I'm using mix 1.4.2, rebar 2.6.4, rebar3 3.3.2
* How mix gives me the error:  `/Users/dani/.mix/rebar3 bare compile --paths "/private/tmp/lofasz/voiceover_core/_build/test/lib/*/ebin"`
* How i managed to get it running: `rebar bare compile "/private/tmp/lofasz/voiceover_core/_build/test/lib/*/ebin"`

Speculations:
* Maybe mix is using a wrong rebar version to compile the project?

Hope it helps!
Reg,
-Dan

**Comment by echofoxxx** [comment] 2017-03-14 07:10
If anyone is getting the following error when using `setup` in an Elixir/Mix project :

```
Unable to run post hooks for 'compile', command 'escriptize' not found.
** (Mix) Could not compile dependency :setup, "/home/ubuntu/.mix/rebar3 bare compile --paths "/var/app/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile setup", update it with "mix deps.update setup" or clean it with "mix deps.clean setup"
```

It can be solved by instructing mix to use `rebar2` instead of `rebar3` :

```
defp deps do
    [
    	{:setup, github: "uwiger/setup", manager: :rebar, override: true}
    ]
end
```

Took me a while to get this working with `exometer`.

**Comment by jvanek** [comment] 2017-06-20 20:51
Thanks ! We're on Elixir 1.4/Erlang 19, it becomes tricky to get all dependencies compile. But the last tip from echofoxxx works perfectly.

**Comment by uwiger** [comment] 2017-09-08 16:30
Closing this. Please start a new issue if there is still a problem.

**Closed by uwiger** 2017-09-08 16:31 UTC
